FROM node:22.14.0-alpine AS runner

WORKDIR /app

ARG PHASE

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN npm install -g sharp@0.33.5

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY ./apps/cart/.next/standalone ./
COPY ./apps/cart/public ./public

# Custom server
COPY ./apps/cart/server/dist/server.js ./server.js
COPY ./node_modules/esbuild ./node_modules/esbuild
COPY ./node_modules/core-js ./node_modules/core-js

RUN chown -R nextjs:nodejs .

USER nextjs

ENV PORT 3000
ENV HOST "0.0.0.0"
ENV NODE_ENV production
ENV PHASE ${PHASE}
ENV NEXT_SHARP_PATH /usr/local/lib/node_modules/sharp

EXPOSE ${PORT}

CMD ["node", "--inspect", "server.js"]
