name: Create & Update comment
description: Create or update comment on PR

inputs:
  comment-author:
    description: The author of the comment
    default: 'github-actions[bot]'
  body-includes:
    description: The body of the comment
    required: true
  body:
    description: The body of the comment
    required: true


runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: ${{ inputs.comment-author }}
        body-includes: ${{ inputs.body-includes }}
    - name: Create comment for affected
      if: steps.find_comment.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ inputs.body }}
    - name: Update comment for affected
      if: steps.find_comment.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        edit-mode: replace
        body: ${{ inputs.body }}
