apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.application.name }}-pdb
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      labelName: {{ .Values.application.name }}-pods
