apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: pods-port
      protocol: TCP
      name: {{ .Values.application.name }}-service-port
  selector:
    labelName: {{ .Values.application.name }}-pods
