name: Read affected apps
description: Read affected apps to be used in other jobs

inputs:
  workflow:
    description: The workflow file to download the artifact from
    default: verification_pull_request.yml
  artifact_path:
    description: The path to the artifact
    required: true
  exclude:
    description: The apps to exclude
    required: false

outputs:
  affected:
    description: The affected apps
    value: ${{ steps.readAffected.outputs.AFFECTED }}

runs:
  using: composite
  steps:
    - name: Download affected for affected
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow }}
        pr: ${{github.event.pull_request.number}}
        name: affected#${{ github.event.pull_request.number }}
        path: ${{ inputs.artifact_path }}
    - name: Setup artifact path
      shell: bash
      run: echo "ARTIFACT_PATH=${{ inputs.artifact_path }}" >> $GITHUB_ENV
    - name: Read affected
      id: readAffected
      shell: bash
      run: |
        # Get affected apps
        AFFECTED_APPS=$(cat $ARTIFACT_PATH/env)
        
        EXCLUDE_LIST="${{ inputs.exclude }}"
    
        # Convert exclude list to array (newline-separated)
        if [ -n "$EXCLUDE_LIST" ]; then
          IFS=$'\n' read -r -a EXCLUDE_ARRAY <<<"$EXCLUDE_LIST"
        else
          EXCLUDE_ARRAY=()
        fi

        AFFECTED_LIST=$(echo "$AFFECTED_APPS" | jq -r '.[]')
        for EXCLUDE in "${EXCLUDE_ARRAY[@]}"; do
          AFFECTED_LIST=$(echo "$AFFECTED_LIST" | grep -v -x "$EXCLUDE")
        done

        AFFECTED_LIST=$(echo "$AFFECTED_LIST" | jq -Rsc 'split("\n")[:-1]')
        echo $AFFECTED_LIST
        echo "AFFECTED=$AFFECTED_LIST" >> $GITHUB_OUTPUT
