on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup/pnpm/save-cache
